[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/neosnippet.vim"

[[plugins]]
repo = "Shougo/neocomplete.vim"

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "Shougo/unite.vim"

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = "michalbachowski/vim-wombat256mod"

[[plugins]]
repo = "Shougo/vimshell"
rev  = "3787e5"
