source ~/dotfiles/vim/vimrc.basic
source ~/dotfiles/vim/vimrc.dein

filetype plugin indent on
syntax enable
colorscheme Tomorrow-Night-Eighties

set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim
